USE SoftUni

/*SELECT ALL RECORDS FROM THE TOWNS*/
SELECT * FROM Towns

/*SELECT ALL RECORDS FROM DEPARTMENTS*/
SELECT * FROM Departments

/*SELECT ALL RECORDS FROM EMPLOYEES*/
SELECT* FROM  Employees 
