USE Demo

SELECT * FROM Triangles

/*Arithmetic operations*/
SELECT Id,
	(A*B)/2 AS AREA
	FROM Triangles

/*PI*/
SELECT PI()

/*ABSOLUT VALUE*/
SELECT ABS(-256)
SELECT ABS(256)

/*SQUARE*/ 
SELECT SQUARE(2)

/*FIND THE LENGHT OF LINE BY GIVEN COORDINATES OF THE END POINTS*/
SELECT * FROM Lines
SELECT Id, X1,Y1,X2,Y2,
	SQRT(SQUARE(X1-X2) + SQUARE(Y1-Y2))
	AS LENGHT
	FROM Lines

/*POWER*/
SELECT POWER(12,2)

/*ROUND*/
SELECT ROUND(18.597,0) /*19.000*/
SELECT ROUND(18.597,2) /*18.600*/
SELECT ROUND(18.597,-1) /*20.000*/

/*FLOOR*/
SELECT FLOOR(18.597) /*18*/

/*CEILING*/
SELECT CEILING(18.597) /*19*/

/*PROBLEM PALLETS*/----
SELECT [Name],Quantity,
	CEILING(
		CEILING(
			CAST(Quantity AS FLOAT)/BoxCapacity)/PalletCapacity) AS [NUMBER OF PALLETS]
	FROM Products

