/*CONVERT*/
SELECT CONVERT(date, '01/01/2019')

/*CAST*/
SELECT CAST(2.5 AS INT) /*CAST DOUBLE TO INT*/

/*ISNULL*/ /*THIS FUNC IS ONLY FOR MICROSOFT SQL*/
USE SoftUni
SELECT ProjectID,Name,
	ISNULL(CAST(EndDate AS VARCHAR), 'NOT FINISHED') /*IF IS NULL CHAGE TO NOT FINISH*/
	FROM Projects

/*COALESCE*/ /*ANOTHER METHOD ISNULL*/
SELECT ProjectID,Name,
	COALESCE(CAST(EndDate AS VARCHAR), 'NOT FINISHED') /*IF IS NULL CHAGE TO NOT FINISH*/
	FROM Projects

SELECT COALESCE(NULL,NULL, 'SADADA',NULL,'QSSS') /*RETURN FIRST NOT NULL VALUE*/

/*OFFSET*/
USE SoftUni

SELECT EmployeeID,FirstName,LastName
	FROM Employees
	ORDER BY EmployeeID
	OFFSET 10 ROWS /*SKIP 10 ROWS*/

/*FETCH*/
SELECT EmployeeID,FirstName,LastName
	FROM Employees
	ORDER BY EmployeeID
	OFFSET 10 ROWS
	FETCH NEXT 5 ROWS ONLY /*SIK FIRST 10 AND GET 5 ROWS*/

/*ROW_NUMBER*/
SELECT 
	EmployeeID,FirstName,LastName,
	ROW_NUMBER() OVER
	(ORDER BY FirstName)
	FROM Employees /*NOT REMOVE DUBLICATE (WE CAN USE PRIMARY KEY)*/

/*RANK*/
SELECT 
	EmployeeID,FirstName,LastName,
	RANK() OVER
	(ORDER BY FirstName)
	FROM Employees /*CAN`T USE PRIMARY KEY*/


/*DENSE_RANK*/
SELECT 
	EmployeeID,FirstName,LastName,
	DENSE_RANK() OVER
	(ORDER BY FirstName)
	FROM Employees 