CREATE TABLE Mountains
(
	Id INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL
);

CREATE TABLE Peaks
(
	Id INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	MountainId INT NOT NULL,
	CONSTRAINT FK_Peaks_MountainsId 
		FOREIGN KEY (MountainId)
		REFERENCES Mountains(Id)
)