CREATE TABLE Drivers
(
	DriverID INT PRIMARY KEY,
	DriverName VARCHAR(50)
)

CREATE TABLE Cars
(
	CarID INT PRIMARY KEY,
	DriverID INT,
	CONSTRAINT FK_Car_Driver FOREIGN KEY (DriverID)
	REFERENCES Drivers(DriverID) ON DELETE CASCADE
)