/*SELECT*/
/*WHEN WE WANT TO GET INF OF ANOTHER DATABES(NOT CURENT DATABASE)*/
SELECT [NAME] 
	FROM SoftUni.dbo.Towns

/*USE SELECT FUNC*/
SELECT TownID ,[NAME] 
	FROM Towns;

SELECT  TownID, [Name] , LEN([Name])/*GET STRING LENGHT*/  
	FROM Towns; /*FIRST METHODS TO GET TABLE FORM DATABASE*/

SELECT  TownID, [Name] , SUBSTRING([Name],1,1)/*GET FIRST CHAR NAME*/  
	FROM Towns; /*FIRST METHODS TO GET TABLE FORM DATABASE*/

SELECT  TownID, [Name] , LEFT([Name],1)/*GET FIRST CHAR NAME*/ 
	FROM Towns; /*FIRST METHODS TO GET TABLE FORM DATABASE*/

/*SELECT AND SET NAME OF COLUM US KEY WORD 'AS'*/
SELECT TownID,[Name], LEN([Name]) AS Lenght/*SET NAME OF COLUM*/
	FROM Towns
/*SELECT AND SET NAME OF COLUM*/
SELECT  TownID, [Name] ,LEN([Name]) AS Lenght, SUBSTRING([Name],1,1) AS FirstLetter
	FROM Towns; /*FIRST METHODS TO GET TABLE FORM DATABASE*/

/*SELECT ALL COL OF TABLE*/
SELECT * FROM Towns;

/*ORDER BY NAME*/
SELECT TownID,[Name] ,LEFT([NAME],1)
	FROM Towns
	ORDER BY [Name];

/*SELECT AND WHERE*/
SELECT *
	FROM Towns
	WHERE Name = 'Sofia'

/*WHERE WITH EXPRESSION*/
SELECT *
	FROM Towns
	WHERE LEFT([NAME],1) = 'S'

/*USE SELECT, JOIN*/
 SELECT * 
	FROM Towns
	JOIN Addresses ON Towns.TownID = Addresses.TownID

/*USE SELECT, JOIN, WHERE*/
 SELECT * 
	FROM Towns
	JOIN Addresses ON Towns.TownID = Addresses.TownID
	WHERE Name = 'Seattle'


 

	   