/*04. Delete*/
DELETE FROM ProductsClients WHERE ClientId = 11
DELETE FROM Invoices WHERE ClientId =11
DELETE FROM Clients WHERE SUBSTRING(NumberVAT,1,2)='IT'


SELECT *FROM Clients
WHERE NumberVAT LIKE '%IT%' /*SEARCH WHERE HAVE 'IT'*/
